name: "CI"
on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: [ '12', '10', '8' ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run build
      - run: npm test
